
services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    pull_policy: build
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "${PWA_NGINX__PORT:-80}:80"
    networks:
      - local
    env_file:
      - stack.env

  backend:
    container_name: backend
    restart: unless-stopped
    pull_policy: build
    build:
      context: ./pwa-blog/
      dockerfile: ./backend/Dockerfile
    environment:
      - TZ=Europe/Lisbon
    env_file:
      - stack.env
    networks:
      - local

  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    pull_policy: build
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mongodb-data:
  mongodb-config:
